# Generated by Django 2.0.1 on 2020-04-07 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_category',
            fields=[
                ('business_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'p_business_category',
            },
        ),
        migrations.CreateModel(
            name='Business_sub_category',
            fields=[
                ('business_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_sub_category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'p_business_sub_category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'p_city',
            },
        ),
        migrations.CreateModel(
            name='Company_type',
            fields=[
                ('company_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'p_company_type',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('shortname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'p_country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'p_currency',
            },
        ),
        migrations.CreateModel(
            name='Currency_type',
            fields=[
                ('currency_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'p_currency_type',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Country')),
            ],
            options={
                'db_table': 'p_location',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'p_office',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Country')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Location')),
            ],
            options={
                'db_table': 'p_person',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('months', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('nickname', models.CharField(max_length=250)),
                ('website', models.URLField(max_length=250)),
                ('street_address', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
                ('youtube', models.CharField(max_length=250)),
                ('msn', models.CharField(max_length=250)),
                ('business_tag', models.CharField(max_length=250)),
                ('company_founded_months', models.CharField(max_length=250)),
                ('company_founded_year', models.CharField(max_length=250)),
                ('skype', models.CharField(max_length=250)),
                ('local_time', models.CharField(max_length=250)),
                ('company_email', models.CharField(max_length=250)),
                ('categories', models.CharField(max_length=250)),
                ('Pintertest', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('annual_turn_over', models.CharField(max_length=250)),
                ('year_of_estd', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=250)),
                ('linkldn', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=250)),
                ('Company_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Company_type')),
                ('Currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Currency')),
                ('Currency_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Currency_type')),
                ('businnes_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Business_category')),
                ('businnes_sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Business_sub_category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Country')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Location')),
            ],
        ),
        migrations.CreateModel(
            name='social_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'p_social_sites',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Country')),
            ],
            options={
                'db_table': 'p_state',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.State'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.State'),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.State'),
        ),
    ]
